x: 3.0 #The x coordinate of the lower left corner of a rectangle
y: 2.0 #The y coordinate of the lower left corner of a rectangle
width: 4.0 #The width of the rectangle
height: 5.0 #The height of the rectangle
trans_vel: 2.0 #The translational velocity of the robot
rot_vel: 1.0 #The rotational velocity of the robot
frequency: 100 # The frequency of the control loop
